services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: swager
      POSTGRES_PASSWORD: NikFast65
      POSTGRES_DB: swagadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://swager:NikFast65@postgres:5432/swagadb

volumes:
  postgres_data:
